
MOVEMENT_DISTANCE = 25

function init(self)
	-- Animate the title back and forth
	local title_node = gui.get_node('title')
	gui.animate(title_node,
				'position.y',
				gui.get_position(title_node).y - MOVEMENT_DISTANCE,
				gui.EASING_INOUTSINE,
				1,
				0,
				nil,
				gui.PLAYBACK_LOOP_PINGPONG,
				10)

	-- Set the version number
	local version_node = gui.get_node('version')
	gui.set_text(version_node, 'v'..sys.get_config('project.version'))
end